# env and task
env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  time_frames: [1, 5, 15, 1]
  window_sizes: [12, 8, 8, 24]
  freqs: ["Min", "Min", "Min", "H"]
  execute_on: 5
  initial_cash: 1000
  transaction_fee: 0.015
  slippage: 0.01
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  backend: gym

# logger
logger:
  backend: wandb
  project_name: TorchTrade-Offline
  exp_name: iql
  group_name: null
  eval_iter: 200
  eval_steps: 1000
  mode: online
  eval_envs: 5
  video: False

# replay buffer
replay_buffer:
  batch_size: 256
  data_path: "/home/sebastian/Documents/TorchTrade/torchrl_alpaca_env/real_live_data/td_new4.pt"
  buffer_size: 10000
  r2g_gamma: 0.99

# optimization
optim:
  device: null
  lr: 3e-4
  weight_decay: 0.0
  gradient_steps: 40000

# network
model:
  hidden_sizes: [256, 256]
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1

# loss
loss: 
  loss_function: l2
  gamma: 0.99
  tau: 0.005
  hard_update_interval: 10


# IQL specific hyperparameter
  temperature: 3.0
  expectile: 0.7

compile:
  compile: False
  compile_mode:
  cudagraphs: False