# env and task
env:
  name: HalfCheetah-v4
  task: ""
  exp_name: ${logger.exp_name}
  n_samples_stats: 1000
  seed: 0
  backend: gym

# logger
logger:
  backend: wandb
  project_name: TorchTrade-Offline
  exp_name: iql
  group_name: null
  eval_iter: 1000
  eval_steps: 1000
  mode: online
  eval_envs: 5
  video: False

# replay buffer
replay_buffer:
  batch_size: 256
  data_path: "/home/sebastian/Documents/TorchTrade/torchrl_alpaca_env/real_live_data/td_iter3.pt"
  buffer_size: 10000
  r2g_gamma: 0.99

# optimization
optim:
  device: null
  lr: 3e-4
  weight_decay: 0.0
  gradient_steps: 2500

# network
model:
  hidden_sizes: [256, 256]
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1

# loss
loss: 
  loss_function: l2
  gamma: 0.99
  tau: 0.005
  hard_update_interval: 10


# IQL specific hyperparameter
  temperature: 3.0
  expectile: 0.7

compile:
  compile: False
  compile_mode:
  cudagraphs: False