env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  freqs: ["Min", "Min", "Min", "Hour"]
  time_frames: [1, 5, 15, 60]
  window_sizes: [12, 8, 8, 24]
  execute_on: 5
  initial_cash: 1000
  transaction_fee: 0.015
  slippage: 0.01
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 5
  eval_envs: 2

  # collector
collector:
  device: 
  frames_per_batch: 4096
  total_frames: 100_000_000

# logger
logger:
  mode: online
  backend: wandb
  project_name: TorchTrade-Online
  group_name: null
  exp_name: ppo
  test_interval: 100_000
  num_test_episodes: 1

# Optim
optim:
  lr: 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True
  device:

# loss
loss:
  gamma: 0.9
  mini_batch_size: 1024
  ppo_epochs: 3
  gae_lambda: 0.95
  clip_epsilon: 0.1
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.01
  loss_critic_type: l2

compile:
  compile: False
  compile_mode:
  cudagraphs: False