env:
  name: SeqFuturesEnv
  symbol: "BTC/USD"
  freqs: ["Min"]
  time_frames: [15]
  window_sizes: [32]
  execute_on: [15, "Min"]
  initial_cash: [1000, 5000]
  transaction_fee: 0.0004  # 0.04% typical futures fee
  slippage: 0.001
  bankrupt_threshold: 0.1
  leverage: 5  # 5x leverage
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 10
  eval_envs: 2
  data_path: Sebasdi/TorchTrade_btcusd_spot_1m_12_2024_to_09_2025

# collector
collector:
  device:
  frames_per_batch: 100000
  total_frames: 100_000_000

# logger
logger:
  mode: online
  backend: wandb
  project_name: TorchTrade-Futures
  group_name: ${env.name}
  exp_name: ppo_futures
  test_interval: 1_000_000
  num_test_episodes: 1

# model
model:
  activation: tanh

# optimization
optim:
  lr: 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True
  device:

# loss
loss:
  gamma: 0.9
  mini_batch_size: 33333
  ppo_epochs: 3
  gae_lambda: 0.95
  clip_epsilon: 0.1
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.01
  loss_critic_type: l2

compile:
  compile: False
  compile_mode:
  cudagraphs: False
