env:
  name: OneStepTradingEnv
  trading_mode: "spot"
  # only used in SeqLongOnlySLTPEnv
  stoploss_levels: [-0.02, -0.04]
  takeprofit_levels: [0.04, 0.08]
  symbol: "BTC/USD"
  time_frames: ["5Min", "15Min"]
  window_sizes: [10, 10]
  execute_on: "15Min"
  initial_cash: [1000, 5000]
  transaction_fee: 0.0025 
  slippage: 0.001
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 8
  eval_envs: 2
  data_path: Torch-Trade/BTCUSD_sport_1m_12_2024_to_09_2025
  test_split_start: 2025-01-01

  # collector
collector:
  device: 
  frames_per_batch: 800 # 5 envs -> 1000 steps per rollout execute on 5 min -> ~ 3.5 days per rollout
  total_frames: 100_000_000

# logger
logger:
  mode: online
  backend: wandb
  project_name: TorchTrade-Online
  group_name: ${env.name}
  exp_name: grpo
  test_interval: 8000
  num_test_episodes: 1


# Optim
optim:
  lr: 2.5e-4
  device:

loss:
  entropy_coef: 0.01

compile:
  compile: False
  compile_mode:
  cudagraphs: False

# Hydra configuration - saves outputs in example directory
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
