
# task and env
env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  time_frames: ["1Hour"]
  window_sizes: [48]
  execute_on: "1Hour"
  initial_cash: [1000, 5000]
  action_levels: [0.0, 1.0]
  transaction_fee: 0.0
  slippage: 0.0
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 1
  eval_envs: 1
  data_path: Torch-Trade/btcusdt_spot_1m_03_2023_to_12_2025
  test_split_start: "2025-01-01"

# collector
collector:
  device: gpu
  init_random_frames: 10_000
  frames_per_batch: 500
  max_frames_per_traj: 10000
  total_frames: 2000000

# replay buffer
replay_buffer:
  prb: 0 # use prioritized experience replay
  size: 100_000
  scratch_dir: null

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.99
  batch_size: 32
  lr: 3.0e-4
  weight_decay: 1e-5
  target_update_polyak: 0.995
  target_entropy_weight: 0.8
  target_entropy: "auto"
  loss_function: smooth_l1 #l2

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  device: null

compile:
  compile: False
  compile_mode:
  cudagraphs: False

# logging
logger:
  backend: wandb
  project_name: TorchTrade-Online
  group_name: null
  exp_name: dSAC
  mode: online
  eval_iter: 5_000

# Hydra configuration - saves outputs in example directory
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}