
# task and env
env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  time_frames: ["5Min", "15Min"]
  window_sizes: [10, 10]
  execute_on: "15Min"
  initial_cash: 1000
  transaction_fee: 0.015
  slippage: 0.01
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 5
  eval_envs: 1
  data_path: Sebasdi/TorchTrade_btcusd_spot_1m_12_2024_to_09_2025
  test_split_start: "2025-01-01"

# collector
collector:
  device: cpu
  init_random_frames: 10000
  frames_per_batch: 5000
  max_frames_per_traj: 100000
  total_frames: 2000000

# replay buffer
replay_buffer:
  prb: 0 # use prioritized experience replay
  size: 1000000
  scratch_dir: null

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.9
  batch_size: 256
  lr: 3.0e-4
  weight_decay: 0.0
  target_update_polyak: 0.995
  target_entropy_weight: 0.2
  target_entropy: "auto"
  loss_function: l2
  # default is 0.98 but needs to be decreased for env
  # with small action space

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  device: null

compile:
  compile: False
  compile_mode:
  cudagraphs: False

# logging
logger:
  backend: wandb
  project_name: TorchTrade-Online
  group_name: null
  exp_name: dSAC
  mode: online
  eval_iter: 20000
  video: False