# env and task
env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  time_frames: ["5Min", "15Min"]
  window_sizes: [10, 10]
  execute_on: "5Min"
  initial_cash: 1000
  transaction_fee: 0.015
  slippage: 0.01
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 5
  eval_envs: 1
  data_path: Torch-Trade/btcusdt_spot_1m_03_2023_to_12_2025
  test_split_start: "2025-01-01"

# logger
logger:
  backend: wandb
  project_name: TorchTrade-Online
  exp_name: iql
  group_name: null
  eval_iter: 20000
  mode: online

# replay buffer
replay_buffer:
  buffer_size: 1000000
  batch_size: 256
  prb: false
  scratch_dir: null
  device: cpu
  prefetch: 3

# collector
collector:
  device: cpu
  init_random_frames: 10000
  frames_per_batch: 5000
  max_frames_per_traj: 100000
  total_frames: 2000000

# optimization
optim:
  device: null
  lr: 3e-4
  weight_decay: 0.0
  utd_ratio: 1

# network
model:
  hidden_sizes: [256, 256]
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1

# loss
loss: 
  loss_function: l2
  gamma: 0.4 # 0.95
  tau: 0.005
  hard_update_interval: 1000


# IQL specific hyperparameter
  temperature: 3.0
  expectile: 0.7

compile:
  compile: False
  compile_mode:
  cudagraphs: False