env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  time_frames: ["5Min", "15Min"]
  window_sizes: [10, 10]
  execute_on: "5Min"
  initial_cash: [1000, 5000]
  transaction_fee: 0.015
  slippage: 0.01
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 1

  # collector
collector:
  device: 
  frames_per_batch: 100
  total_frames: 1000

# logger
logger:
  mode: online
  backend: wandb
  project_name: TorchTrade-Online
  group_name: null
  exp_name: human

