env:
  name: SeqLongOnlyEnv
  symbol: "BTC/USD"
  freqs: ["Min", "Min", "Min", "Hour"]
  time_frames: [1, 5, 15, 60]
  window_sizes: [12, 8, 8, 24]
  execute_on: 5
  initial_cash: [1000, 5000]
  transaction_fee: 0.015
  slippage: 0.01
  bankrupt_threshold: 0.1
  exp_name: ${logger.exp_name}
  seed: 0
  train_envs: 1

  # collector
collector:
  device: 
  frames_per_batch: 100
  total_frames: 1000

# logger
logger:
  mode: online
  backend: wandb
  project_name: TorchTrade-Online
  group_name: null
  exp_name: human

